# create portfolio model

from dataclasses import field
from pydantic import BaseModel,Field
from typing import List,Dict 

class HoldingSummary(BaseModel):
    """Represents a single holding in the portfolio"""

    symbol:str = Field(...,description="Stock ticker symbol")
    company_name:str = Field(...,description="Name of the company")
    quantity:int=Field(...,ge=0)
    average_buy_price:float=Field(...,ge=0)
    current_price:float=Field(...,ge=0)
    current_value:float=Field(...,ge=0)
    profit_loss:float
    profit_loss_percentage:float
    allocation_percentage:float=Field(...,ge=0,le=100)
    sector:str
    

class PortfolioIntelligence(BaseModel):
    """
    Represents the complete portfolio intelligence generated by the analysis engine"""

    portfolio_value:float=Field(...,ge=0)
    investment_amount:float=Field(...,ge=0)
    total_profit_loss:float
    total_profit_loss_percentage:float
    total_allocation_percentage:float=Field(...,ge=0,le=100)
    diversification_score:float=Field(...,ge=0,le=100,description="Portfolio diversification score (0-10)")
    concentration_risk:str=Field(...,description="Low/Medium/High")
    portfolio_health:str=Field(...,description="Low/Medium/High")
    top_holdings:List[HoldingSummary]
    sector_distribution:Dict[str,float]